// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Modules.Billing.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Modules.Billing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.FeeRateRules.FeeRateRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingFrequencyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("billing_frequency_code");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<string>("CalculationMethodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calculation_method_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_type_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaximumAmount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("maximum_amount");

                    b.Property<decimal?>("MinimumAmount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("minimum_amount");

                    b.Property<string>("RuleConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_config");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("rule_name");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("unit_rate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("FeeTypeId", "BuildingId", "EffectiveFrom");

                    b.ToTable("fee_rate_rules", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_fee_rate_rules_amount_range", "minimum_amount IS NULL OR maximum_amount IS NULL OR minimum_amount <= maximum_amount");

                            t.HasCheckConstraint("CK_fee_rate_rules_effective_dates", "effective_to IS NULL OR effective_to >= effective_from");

                            t.HasCheckConstraint("CK_fee_rate_rules_maximum_amount_non_negative", "maximum_amount IS NULL OR maximum_amount >= 0");

                            t.HasCheckConstraint("CK_fee_rate_rules_minimum_amount_non_negative", "minimum_amount IS NULL OR minimum_amount >= 0");

                            t.HasCheckConstraint("CK_fee_rate_rules_unit_rate_non_negative", "unit_rate >= 0");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.FeeTypes.FeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultBillingFrequencyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_billing_frequency_code");

                    b.Property<string>("DefaultCalculationMethodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_calculation_method_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("fee_types", "billing");
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.InvoiceItems.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculationMethodCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calculation_method_code_snapshot");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FeeCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fee_code_snapshot");

                    b.Property<string>("FeeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fee_name_snapshot");

                    b.Property<Guid?>("FeeRateRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_rate_rule_id");

                    b.Property<Guid?>("FeeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_type_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("line_amount");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("unit_rate");

                    b.HasKey("Id");

                    b.HasIndex("FeeRateRuleId");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_items", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_invoice_items_line_amount_non_negative", "line_amount >= 0");

                            t.HasCheckConstraint("CK_invoice_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("CK_invoice_items_unit_rate_non_negative", "unit_rate >= 0");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.InvoiceStatusHistories.InvoiceStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_status_history", "billing");
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApartmentUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("apartment_unit_id");

                    b.Property<DateOnly>("BillingPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("billing_period_end");

                    b.Property<DateOnly>("BillingPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("billing_period_start");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("invoice_number");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentUnitId");

                    b.HasIndex("DueDate");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("ApartmentUnitId", "BillingPeriodStart", "BillingPeriodEnd")
                        .IsUnique();

                    b.ToTable("invoices", "billing", t =>
                        {
                            t.HasCheckConstraint("CK_invoices_billing_period", "billing_period_end >= billing_period_start");

                            t.HasCheckConstraint("CK_invoices_cancelled_fields", "(status <> 'CANCELLED') OR (cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL AND cancellation_reason IS NOT NULL)");

                            t.HasCheckConstraint("CK_invoices_due_date", "issue_date IS NULL OR due_date IS NULL OR due_date >= issue_date");

                            t.HasCheckConstraint("CK_invoices_issued_fields", "(status <> 'ISSUED') OR (issue_date IS NOT NULL AND issued_at IS NOT NULL AND issued_by IS NOT NULL AND cancelled_at IS NULL AND cancelled_by IS NULL)");

                            t.HasCheckConstraint("CK_invoices_subtotal_non_negative", "subtotal >= 0");

                            t.HasCheckConstraint("CK_invoices_total_amount_non_negative", "total_amount >= 0");

                            t.HasCheckConstraint("CK_invoices_total_matches_subtotal", "total_amount = subtotal");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.FeeRateRules.FeeRateRule", b =>
                {
                    b.HasOne("PropFlow.Modules.Billing.Domain.FeeTypes.FeeType", "FeeType")
                        .WithMany("RateRules")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.InvoiceItems.InvoiceItem", b =>
                {
                    b.HasOne("PropFlow.Modules.Billing.Domain.FeeRateRules.FeeRateRule", "FeeRateRule")
                        .WithMany()
                        .HasForeignKey("FeeRateRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Modules.Billing.Domain.FeeTypes.FeeType", "FeeType")
                        .WithMany()
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Modules.Billing.Domain.Invoices.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeRateRule");

                    b.Navigation("FeeType");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.InvoiceStatusHistories.InvoiceStatusHistory", b =>
                {
                    b.HasOne("PropFlow.Modules.Billing.Domain.Invoices.Invoice", "Invoice")
                        .WithMany("StatusHistory")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.FeeTypes.FeeType", b =>
                {
                    b.Navigation("RateRules");
                });

            modelBuilder.Entity("PropFlow.Modules.Billing.Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
