// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Modules.AiRecommendation.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Modules.AiRecommendation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiRecommendationDbContext))]
    partial class AiRecommendationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai_recommendation")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Modules.AiRecommendation.Domain.Recommendations.AiRecommendationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision");

                    b.Property<string>("FinalAction")
                        .HasColumnType("text")
                        .HasColumnName("final_action");

                    b.Property<bool?>("FinalMaintenanceRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("final_maintenance_required");

                    b.Property<string>("FinalPriorityCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("final_priority_code");

                    b.Property<string>("FinalResourcePlan")
                        .HasColumnType("text")
                        .HasColumnName("final_resource_plan");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id");

                    b.HasIndex("Decision");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.HasIndex("ReviewedBy");

                    b.ToTable("ai_recommendation_reviews", "ai_recommendation", t =>
                        {
                            t.HasCheckConstraint("CK_ai_recommendation_reviews_corrected_note", "(decision <> 'CORRECTED') OR review_note IS NOT NULL");

                            t.HasCheckConstraint("CK_ai_recommendation_reviews_final_fields", "(decision IN ('CONFIRMED', 'CORRECTED', 'OVERRIDDEN') AND final_priority_code IS NOT NULL) OR (decision = 'REJECTED' AND final_priority_code IS NULL AND final_maintenance_required IS NULL AND final_action IS NULL AND final_resource_plan IS NULL)");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.AiRecommendation.Domain.Recommendations.AiRequestRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_hash");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<bool?>("MaintenanceRecommended")
                        .HasColumnType("boolean")
                        .HasColumnName("maintenance_recommended");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model_name");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ReasoningSummary")
                        .HasColumnType("text")
                        .HasColumnName("reasoning_summary");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text")
                        .HasColumnName("recommended_action");

                    b.Property<string>("RecommendedResourceSummary")
                        .HasColumnType("text")
                        .HasColumnName("recommended_resource_summary");

                    b.Property<string>("RecommendedResourcesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_resources");

                    b.Property<string>("RunStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("run_status");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_request_id");

                    b.Property<string>("SuggestedPriorityCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("suggested_priority_code");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id");

                    b.HasIndex("RunStatus");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("SuggestedPriorityCode");

                    b.HasIndex("ServiceRequestId", "AttemptNo")
                        .IsUnique();

                    b.ToTable("ai_request_recommendations", "ai_recommendation", t =>
                        {
                            t.HasCheckConstraint("CK_ai_request_recommendations_attempt_no", "attempt_no >= 1");

                            t.HasCheckConstraint("CK_ai_request_recommendations_failed_fields", "(run_status <> 'FAILED') OR (error_message IS NOT NULL AND suggested_priority_code IS NULL AND maintenance_recommended IS NULL AND recommended_action IS NULL AND recommended_resource_summary IS NULL AND recommended_resources IS NULL AND reasoning_summary IS NULL)");

                            t.HasCheckConstraint("CK_ai_request_recommendations_latency", "latency_ms IS NULL OR latency_ms >= 0");

                            t.HasCheckConstraint("CK_ai_request_recommendations_success_fields", "(run_status <> 'SUCCESS') OR (suggested_priority_code IS NOT NULL AND error_message IS NULL)");

                            t.HasCheckConstraint("CK_ai_request_recommendations_tokens", "(input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0) AND (total_tokens IS NULL OR total_tokens >= 0)");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.AiRecommendation.Domain.Recommendations.AiRecommendationReview", b =>
                {
                    b.HasOne("PropFlow.Modules.AiRecommendation.Domain.Recommendations.AiRequestRecommendation", "Recommendation")
                        .WithOne("Review")
                        .HasForeignKey("PropFlow.Modules.AiRecommendation.Domain.Recommendations.AiRecommendationReview", "RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("PropFlow.Modules.AiRecommendation.Domain.Recommendations.AiRequestRecommendation", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
