// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Modules.Maintenance.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Modules.Maintenance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    partial class MaintenanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maintenance")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceAssignments.MaintenanceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignmentNote")
                        .HasColumnType("text")
                        .HasColumnName("assignment_note");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("MaintenanceTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_task_id");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_user_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ASSIGNED")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt");

                    b.HasIndex("MaintenanceTaskId")
                        .IsUnique()
                        .HasDatabaseName("IX_maintenance_assignments_active_maintenance_task_id")
                        .HasFilter("\"status\" IN ('ASSIGNED', 'IN_PROGRESS')");

                    b.HasIndex("StaffUserId");

                    b.HasIndex("Status");

                    b.ToTable("maintenance_assignments", "maintenance", t =>
                        {
                            t.HasCheckConstraint("CK_maintenance_assignments_completed_at", "started_at IS NULL OR completed_at IS NULL OR completed_at >= started_at");

                            t.HasCheckConstraint("CK_maintenance_assignments_ended_at", "ended_at IS NULL OR ended_at >= assigned_at");

                            t.HasCheckConstraint("CK_maintenance_assignments_started_at", "started_at IS NULL OR started_at >= assigned_at");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceResults.MaintenanceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_no");

                    b.Property<string>("IssueFound")
                        .HasColumnType("text")
                        .HasColumnName("issue_found");

                    b.Property<Guid>("MaintenanceTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_task_id");

                    b.Property<string>("PartsOrResourcesUsed")
                        .HasColumnType("text")
                        .HasColumnName("parts_or_resources_used");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("SUBMITTED")
                        .HasColumnName("result_status");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkPerformed")
                        .HasColumnType("text")
                        .HasColumnName("work_performed");

                    b.HasKey("Id");

                    b.HasIndex("ResultStatus");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("MaintenanceTaskId", "AttemptNo")
                        .IsUnique();

                    b.ToTable("maintenance_results", "maintenance", t =>
                        {
                            t.HasCheckConstraint("CK_maintenance_results_attempt_no", "attempt_no >= 1");

                            t.HasCheckConstraint("CK_maintenance_results_reviewed_at", "reviewed_at IS NULL OR reviewed_at >= submitted_at");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceSchedules.MaintenanceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<DateTimeOffset?>("PlannedEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end_at");

                    b.Property<DateTimeOffset>("PlannedStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start_at");

                    b.Property<string>("ScheduleCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("schedule_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PlannedStartAt");

                    b.HasIndex("ScheduleCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("maintenance_schedules", "maintenance", t =>
                        {
                            t.HasCheckConstraint("CK_maintenance_schedules_planned_end_at", "planned_end_at IS NULL OR planned_end_at >= planned_start_at");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceTaskActivities.MaintenanceTaskActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("activity_type");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("MaintenanceTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_task_id");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MaintenanceTaskId");

                    b.ToTable("maintenance_task_activities", "maintenance");
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<DateTimeOffset?>("PlannedStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start_at");

                    b.Property<string>("PriorityCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("priority_code");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid?>("SourceComplaintId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_complaint_id");

                    b.Property<Guid?>("SourceServiceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_service_request_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("task_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("DueAt");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PriorityCode");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SourceComplaintId");

                    b.HasIndex("SourceServiceRequestId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskNumber")
                        .IsUnique();

                    b.ToTable("maintenance_tasks", "maintenance", t =>
                        {
                            t.HasCheckConstraint("CK_maintenance_tasks_closed_at", "completed_at IS NULL OR closed_at IS NULL OR closed_at >= completed_at");

                            t.HasCheckConstraint("CK_maintenance_tasks_completed_at", "started_at IS NULL OR completed_at IS NULL OR completed_at >= started_at");

                            t.HasCheckConstraint("CK_maintenance_tasks_due_at", "planned_start_at IS NULL OR due_at IS NULL OR due_at >= planned_start_at");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceAssignments.MaintenanceAssignment", b =>
                {
                    b.HasOne("PropFlow.Modules.Maintenance.Domain.MaintenanceTasks.MaintenanceTask", "MaintenanceTask")
                        .WithMany("Assignments")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceTask");
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceResults.MaintenanceResult", b =>
                {
                    b.HasOne("PropFlow.Modules.Maintenance.Domain.MaintenanceTasks.MaintenanceTask", "MaintenanceTask")
                        .WithMany("Results")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceTask");
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceTaskActivities.MaintenanceTaskActivity", b =>
                {
                    b.HasOne("PropFlow.Modules.Maintenance.Domain.MaintenanceAssignments.MaintenanceAssignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropFlow.Modules.Maintenance.Domain.MaintenanceTasks.MaintenanceTask", "MaintenanceTask")
                        .WithMany("Activities")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("MaintenanceTask");
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.HasOne("PropFlow.Modules.Maintenance.Domain.MaintenanceSchedules.MaintenanceSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PropFlow.Modules.Maintenance.Domain.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Assignments");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
