<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/Modules/Authentication/PropFlow.Modules.Authentication.csproj" />
    <ProjectReference Include="../../src/Modules/Administration/PropFlow.Modules.Administration.csproj" />
    <ProjectReference Include="../../src/Modules/PropertyAssets/PropFlow.Modules.PropertyAssets.csproj" />
  </ItemGroup>
</Project>
