// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Modules.Communication.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Modules.Communication.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    [Migration("20260921174754_RemoveBuildingAudienceFromCommunication")]
    partial class RemoveBuildingAudienceFromCommunication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communication")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Modules.Communication.Domain.Announcements.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("WithdrawalReason")
                        .HasColumnType("text")
                        .HasColumnName("withdrawal_reason");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Status");

                    b.ToTable("announcements", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_announcements_content_not_blank", "length(btrim(content)) > 0");

                            t.HasCheckConstraint("CK_announcements_published_state", "(status = 'DRAFT' AND published_at IS NULL AND withdrawn_at IS NULL AND withdrawal_reason IS NULL) OR (status = 'PUBLISHED' AND published_at IS NOT NULL AND withdrawn_at IS NULL AND withdrawal_reason IS NULL AND published_at >= created_at) OR (status = 'WITHDRAWN' AND published_at IS NOT NULL AND withdrawn_at IS NOT NULL AND withdrawal_reason IS NOT NULL AND published_at >= created_at AND withdrawn_at >= published_at)");

                            t.HasCheckConstraint("CK_announcements_title_not_blank", "length(btrim(title)) > 0");

                            t.HasCheckConstraint("CK_announcements_updated_at", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Communication.Domain.Announcements.AnnouncementAudience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("uuid")
                        .HasColumnName("announcement_id");

                    b.Property<Guid?>("ApartmentUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("apartment_unit_id");

                    b.Property<string>("AudienceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("audience_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("ApartmentUnitId");

                    b.HasIndex("AudienceType");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("AnnouncementId", "ApartmentUnitId")
                        .IsUnique()
                        .HasDatabaseName("UX_announcement_audiences_announcement_apartment")
                        .HasFilter("audience_type = 'APARTMENT' AND apartment_unit_id IS NOT NULL");

                    b.HasIndex("AnnouncementId", "AudienceType")
                        .IsUnique()
                        .HasDatabaseName("UX_announcement_audiences_announcement_type_global")
                        .HasFilter("audience_type IN ('ALL_USERS', 'ALL_RESIDENTS')");

                    b.HasIndex("AnnouncementId", "ResidentId")
                        .IsUnique()
                        .HasDatabaseName("UX_announcement_audiences_announcement_resident")
                        .HasFilter("audience_type = 'RESIDENT' AND resident_id IS NOT NULL");

                    b.HasIndex("AnnouncementId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_announcement_audiences_announcement_role")
                        .HasFilter("audience_type = 'ROLE' AND role_id IS NOT NULL");

                    b.ToTable("announcement_audiences", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_announcement_audiences_target", "(audience_type IN ('ALL_USERS', 'ALL_RESIDENTS') AND role_id IS NULL AND apartment_unit_id IS NULL AND resident_id IS NULL) OR (audience_type = 'ROLE' AND role_id IS NOT NULL AND apartment_unit_id IS NULL AND resident_id IS NULL) OR (audience_type = 'APARTMENT' AND role_id IS NULL AND apartment_unit_id IS NOT NULL AND resident_id IS NULL) OR (audience_type = 'RESIDENT' AND role_id IS NULL AND apartment_unit_id IS NULL AND resident_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Communication.Domain.Announcements.AnnouncementVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("uuid")
                        .HasColumnName("announcement_id");

                    b.Property<string>("AudienceSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("audience_snapshot");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text")
                        .HasColumnName("change_reason");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("ContentSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_snapshot");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("StatusSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_snapshot");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_snapshot");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("AnnouncementId", "VersionNo")
                        .IsUnique();

                    b.ToTable("announcement_versions", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_announcement_versions_content_not_blank", "length(btrim(content_snapshot)) > 0");

                            t.HasCheckConstraint("CK_announcement_versions_title_not_blank", "length(btrim(title_snapshot)) > 0");

                            t.HasCheckConstraint("CK_announcement_versions_version_no", "version_no >= 1");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Communication.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("Type");

                    b.HasIndex("RecipientUserId", "IsRead");

                    b.HasIndex("RecipientUserId", "SourceEventId")
                        .IsUnique()
                        .HasFilter("source_event_id IS NOT NULL");

                    b.HasIndex("SourceType", "SourceId");

                    b.ToTable("notifications", "communication", t =>
                        {
                            t.HasCheckConstraint("CK_notifications_message_not_blank", "length(btrim(message)) > 0");

                            t.HasCheckConstraint("CK_notifications_read_state", "(is_read = false AND read_at IS NULL) OR (is_read = true AND read_at IS NOT NULL AND read_at >= created_at)");

                            t.HasCheckConstraint("CK_notifications_source_reference", "(source_type IS NULL AND source_id IS NULL) OR (source_type IS NOT NULL AND source_id IS NOT NULL)");

                            t.HasCheckConstraint("CK_notifications_title_not_blank", "length(btrim(title)) > 0");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.Communication.Domain.Announcements.AnnouncementAudience", b =>
                {
                    b.HasOne("PropFlow.Modules.Communication.Domain.Announcements.Announcement", "Announcement")
                        .WithMany("Audiences")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Announcement");
                });

            modelBuilder.Entity("PropFlow.Modules.Communication.Domain.Announcements.AnnouncementVersion", b =>
                {
                    b.HasOne("PropFlow.Modules.Communication.Domain.Announcements.Announcement", "Announcement")
                        .WithMany("Versions")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Announcement");
                });

            modelBuilder.Entity("PropFlow.Modules.Communication.Domain.Announcements.Announcement", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
