// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Modules.Apartments.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Modules.Apartments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApartmentsDbContext))]
    [Migration("20260930165554_AddApartmentMasterDataFields")]
    partial class AddApartmentMasterDataFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("apartments")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Modules.Apartments.Domain.ApartmentUnits.ApartmentOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApartmentUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("apartment_unit_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("OwnerResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_resident_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("OwnerResidentId");

                    b.HasIndex("ApartmentUnitId", "StartDate")
                        .IsUnique();

                    b.ToTable("apartment_ownerships", "apartments");
                });

            modelBuilder.Entity("PropFlow.Modules.Apartments.Domain.ApartmentUnits.ApartmentUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BathroomCount")
                        .HasColumnType("integer")
                        .HasColumnName("bathroom_count");

                    b.Property<int?>("BedroomCount")
                        .HasColumnType("integer")
                        .HasColumnName("bedroom_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number");

                    b.Property<DateOnly?>("HandoverDate")
                        .HasColumnType("date")
                        .HasColumnName("handover_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_number");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("UsableAreaM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("usable_area_m2");

                    b.HasKey("Id");

                    b.HasIndex("FloorNumber");

                    b.HasIndex("Status");

                    b.HasIndex("UnitNumber")
                        .IsUnique();

                    b.ToTable("apartment_units", "apartments");
                });

            modelBuilder.Entity("PropFlow.Modules.Apartments.Domain.ApartmentUnits.ApartmentOwnership", b =>
                {
                    b.HasOne("PropFlow.Modules.Apartments.Domain.ApartmentUnits.ApartmentUnit", null)
                        .WithMany()
                        .HasForeignKey("ApartmentUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
