// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFlow.Modules.AiClassification.Infrastructure.Persistence;

#nullable disable

namespace PropFlow.Modules.AiClassification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiClassificationDbContext))]
    partial class AiClassificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai_classification")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFlow.Modules.AiClassification.Domain.Classifications.AiClassificationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision");

                    b.Property<Guid?>("FinalCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("final_category_id");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId")
                        .IsUnique();

                    b.HasIndex("Decision");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("ai_classification_reviews", "ai_classification", t =>
                        {
                            t.HasCheckConstraint("CK_ai_classification_reviews_final_category", "(decision IN ('CONFIRMED', 'CORRECTED', 'OVERRIDDEN') AND final_category_id IS NOT NULL) OR (decision = 'REJECTED' AND final_category_id IS NULL)");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.AiClassification.Domain.Classifications.AiRequestClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_no");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_hash");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model_name");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("PredictedCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("predicted_category_id");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ReasoningSummary")
                        .HasColumnType("text")
                        .HasColumnName("reasoning_summary");

                    b.Property<string>("RunStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("run_status");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_request_id");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id");

                    b.HasIndex("PredictedCategoryId");

                    b.HasIndex("RunStatus");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("ServiceRequestId", "AttemptNo")
                        .IsUnique();

                    b.ToTable("ai_request_classifications", "ai_classification", t =>
                        {
                            t.HasCheckConstraint("CK_ai_request_classifications_attempt_no", "attempt_no >= 1");

                            t.HasCheckConstraint("CK_ai_request_classifications_confidence_score", "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)");

                            t.HasCheckConstraint("CK_ai_request_classifications_failed_fields", "(run_status <> 'FAILED') OR (error_message IS NOT NULL AND predicted_category_id IS NULL AND confidence_score IS NULL AND reasoning_summary IS NULL)");

                            t.HasCheckConstraint("CK_ai_request_classifications_latency", "latency_ms IS NULL OR latency_ms >= 0");

                            t.HasCheckConstraint("CK_ai_request_classifications_success_fields", "(run_status <> 'SUCCESS') OR (predicted_category_id IS NOT NULL AND error_message IS NULL)");

                            t.HasCheckConstraint("CK_ai_request_classifications_tokens", "(input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0) AND (total_tokens IS NULL OR total_tokens >= 0)");
                        });
                });

            modelBuilder.Entity("PropFlow.Modules.AiClassification.Domain.Classifications.AiClassificationReview", b =>
                {
                    b.HasOne("PropFlow.Modules.AiClassification.Domain.Classifications.AiRequestClassification", "Classification")
                        .WithOne("Review")
                        .HasForeignKey("PropFlow.Modules.AiClassification.Domain.Classifications.AiClassificationReview", "ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classification");
                });

            modelBuilder.Entity("PropFlow.Modules.AiClassification.Domain.Classifications.AiRequestClassification", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
